package generator

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/manas/cloud/internal/domain"
)

// ComposeGenerator generates docker-compose.yml files.
type ComposeGenerator struct{}

// NewComposeGenerator creates a new ComposeGenerator.
func NewComposeGenerator() *ComposeGenerator {
	return &ComposeGenerator{}
}

// Generate creates a docker-compose.yml for the project.
func (g *ComposeGenerator) Generate(project *domain.Project, outputDir string) error {
	content, err := g.render(project)
	if err != nil {
		return fmt.Errorf("failed to render docker-compose.yml: %w", err)
	}

	return WriteFile(outputDir, "docker-compose.yml", content)
}

func (g *ComposeGenerator) render(project *domain.Project) (string, error) {
	tmpl, err := template.New("compose").Parse(composeTemplate)
	if err != nil {
		return "", err
	}

	data := struct {
		Project    *domain.Project
		HasDB      bool
		HasRedis   bool
		DBType     string
		AppPort    string
	}{
		Project:  project,
		HasDB:    project.TechStack.Database != "",
		HasRedis: project.TechStack.Cache == "Redis",
		DBType:   project.TechStack.Database,
		AppPort:  "8080",
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}

	return buf.String(), nil
}

const composeTemplate = `# docker-compose.yml for {{.Project.Name}}
# Generated by cloud CLI

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: {{.Project.Name}}-app
    ports:
      - "${APP_PORT:-{{.AppPort}}}:{{.AppPort}}"
    environment:
      - ENV=development
{{if .HasDB}}      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:postgres@db:5432/{{.Project.Name}}?sslmode=disable}
{{end}}{{if .HasRedis}}      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
{{end}}{{if .HasDB}}    depends_on:
      db:
        condition: service_healthy
{{end}}{{if .HasRedis}}      redis:
        condition: service_healthy
{{end}}    networks:
      - {{.Project.Name}}-network
    restart: unless-stopped

{{if .HasDB}}  db:
{{if eq .DBType "PostgreSQL"}}    image: postgres:16-alpine
    container_name: {{.Project.Name}}-db
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: {{.Project.Name}}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
{{else if eq .DBType "MySQL"}}    image: mysql:8
    container_name: {{.Project.Name}}-db
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: {{.Project.Name}}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
{{end}}    networks:
      - {{.Project.Name}}-network
    restart: unless-stopped

{{end}}{{if .HasRedis}}  redis:
    image: redis:7-alpine
    container_name: {{.Project.Name}}-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - {{.Project.Name}}-network
    restart: unless-stopped

{{end}}volumes:
{{if .HasDB}}{{if eq .DBType "PostgreSQL"}}  postgres-data:
{{else if eq .DBType "MySQL"}}  mysql-data:
{{end}}{{end}}{{if .HasRedis}}  redis-data:
{{end}}

networks:
  {{.Project.Name}}-network:
    driver: bridge
`
