package generator

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/manas/cloud/internal/domain"
)

// DockerfileGenerator generates Dockerfile files.
type DockerfileGenerator struct{}

// NewDockerfileGenerator creates a new DockerfileGenerator.
func NewDockerfileGenerator() *DockerfileGenerator {
	return &DockerfileGenerator{}
}

// Generate creates a Dockerfile for the project.
func (g *DockerfileGenerator) Generate(project *domain.Project, outputDir string) error {
	content, err := g.render(project)
	if err != nil {
		return fmt.Errorf("failed to render Dockerfile: %w", err)
	}

	return WriteFile(outputDir, "Dockerfile", content)
}

func (g *DockerfileGenerator) render(project *domain.Project) (string, error) {
	tmplStr := g.getTemplate(project)
	tmpl, err := template.New("dockerfile").Parse(tmplStr)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, project); err != nil {
		return "", err
	}

	return buf.String(), nil
}

func (g *DockerfileGenerator) getTemplate(project *domain.Project) string {
	switch project.TechStack.Language {
	case "Go":
		return goDockerfileTemplate
	case "TypeScript":
		return tsDockerfileTemplate
	case "Python":
		return pythonDockerfileTemplate
	default:
		return goDockerfileTemplate
	}
}

const goDockerfileTemplate = `# Dockerfile for {{.Name}}
# Generated by cloud CLI

# Build stage
FROM golang:1.22-alpine AS builder

RUN apk add --no-cache git ca-certificates tzdata

WORKDIR /build

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy source
COPY . .

# Build
ARG VERSION=dev
RUN CGO_ENABLED=0 GOOS=linux go build \
    -ldflags "-s -w -X main.version=${VERSION}" \
    -o app ./cmd/{{.Name}}

# Final stage
FROM alpine:3.19

RUN apk add --no-cache ca-certificates tzdata

# Create non-root user
RUN addgroup -g 1000 appgroup && \
    adduser -u 1000 -G appgroup -s /bin/sh -D appuser

WORKDIR /app

COPY --from=builder /build/app .

RUN chown -R appuser:appgroup /app

USER appuser

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1

ENTRYPOINT ["./app"]
`

const tsDockerfileTemplate = `# Dockerfile for {{.Name}}
# Generated by cloud CLI

# Build stage
FROM node:20-alpine AS builder

WORKDIR /app

# Copy package files
COPY package*.json ./
RUN npm ci

# Copy source and build
COPY . .
RUN npm run build

# Production stage
FROM node:20-alpine

RUN addgroup -g 1000 appgroup && \
    adduser -u 1000 -G appgroup -s /bin/sh -D appuser

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./

RUN chown -R appuser:appgroup /app

USER appuser

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1

CMD ["node", "dist/index.js"]
`

const pythonDockerfileTemplate = `# Dockerfile for {{.Name}}
# Generated by cloud CLI

FROM python:3.12-slim

RUN groupadd -g 1000 appgroup && \
    useradd -u 1000 -g appgroup -s /bin/bash appuser

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application
COPY . .

RUN chown -R appuser:appgroup /app

USER appuser

EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD curl -f http://localhost:8000/health || exit 1

CMD ["python", "-m", "{{.Name}}"]
`
