package generator

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/manas/cloud/internal/domain"
)

// MakefileGenerator generates Makefile files.
type MakefileGenerator struct{}

// NewMakefileGenerator creates a new MakefileGenerator.
func NewMakefileGenerator() *MakefileGenerator {
	return &MakefileGenerator{}
}

// Generate creates a Makefile for the project.
func (g *MakefileGenerator) Generate(project *domain.Project, outputDir string) error {
	content, err := g.render(project)
	if err != nil {
		return fmt.Errorf("failed to render Makefile: %w", err)
	}

	return WriteFile(outputDir, "Makefile", content)
}

func (g *MakefileGenerator) render(project *domain.Project) (string, error) {
	tmpl, err := template.New("makefile").Parse(g.getTemplate(project))
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, project); err != nil {
		return "", err
	}

	return buf.String(), nil
}

func (g *MakefileGenerator) getTemplate(project *domain.Project) string {
	// For cross-platform apps, choose template based on framework
	if project.AppType == domain.AppTypeCrossPlatform && project.AppTypeDetails != nil {
		switch project.AppTypeDetails["framework"] {
		case "flutter":
			return flutterMakefileTemplate
		case "tauri":
			return tauriMakefileTemplate
		case "electron":
			return electronMakefileTemplate
		case "react-native":
			return reactNativeMakefileTemplate
		case "wails":
			return wailsMakefileTemplate
		}
	}

	switch project.TechStack.Language {
	case "Go":
		return goMakefileTemplate
	case "TypeScript":
		return tsMakefileTemplate
	case "Python":
		return pythonMakefileTemplate
	case "Dart":
		return flutterMakefileTemplate
	case "Rust":
		return rustMakefileTemplate
	default:
		return goMakefileTemplate // Default to Go
	}
}

const goMakefileTemplate = `# Makefile for {{.Name}}
# Generated by cloud CLI

.PHONY: help build run test test-coverage lint fmt vet clean deps docker-build docker-run

.DEFAULT_GOAL := help

# Detect OS for cross-platform compatibility
ifeq ($(OS),Windows_NT)
    EXE_EXT := .exe
    RM_CMD := powershell -Command "Remove-Item -Recurse -Force -ErrorAction SilentlyContinue"
    RACE_FLAG :=
else
    EXE_EXT :=
    RM_CMD := rm -rf
    RACE_FLAG := -race
endif

# Variables
APP_NAME := {{.Name}}
VERSION := $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
LDFLAGS := -ldflags "-X main.version=$(VERSION)"

## help: Show this help message
help:
	@echo "Usage: make [target]"
	@echo ""
	@echo "Targets:"
	@echo "  build          Build the application"
	@echo "  run            Run the application"
	@echo "  test           Run all tests"
	@echo "  test-coverage  Run tests with coverage"
	@echo "  lint           Run linter"
	@echo "  fmt            Format code"
	@echo "  vet            Run go vet"
	@echo "  clean          Clean build artifacts"
	@echo "  deps           Download dependencies"

## build: Build the application
build:
	go build $(LDFLAGS) -o bin/$(APP_NAME)$(EXE_EXT) ./cmd/$(APP_NAME)

## run: Run the application
run:
	go run ./cmd/$(APP_NAME)

## test: Run all tests
test:
	go test -v $(RACE_FLAG) -cover ./...

## test-coverage: Run tests with coverage report
test-coverage:
	go test -v $(RACE_FLAG) -coverprofile=coverage.out ./...
	go tool cover -html=coverage.out -o coverage.html

## lint: Run linter
lint:
	golangci-lint run ./...

## fmt: Format code
fmt:
	go fmt ./...
	-goimports -w .

## vet: Run go vet
vet:
	go vet ./...

## clean: Clean build artifacts
clean:
ifeq ($(OS),Windows_NT)
	@powershell -Command "if (Test-Path bin) { Remove-Item -Recurse -Force bin }"
	@powershell -Command "if (Test-Path coverage.out) { Remove-Item -Force coverage.out }"
else
	$(RM_CMD) bin/ coverage.out coverage.html
endif

## deps: Download dependencies
deps:
	go mod download
	go mod tidy

## docker-build: Build Docker image
docker-build:
	docker build -t $(APP_NAME):$(VERSION) .

## docker-run: Run Docker container
docker-run:
	docker run --rm -it $(APP_NAME):$(VERSION)
`

const tsMakefileTemplate = `# Makefile for {{.Name}}
# Generated by cloud CLI

.PHONY: help build dev test lint fmt clean deps

.DEFAULT_GOAL := help

# Variables
APP_NAME := {{.Name}}

## help: Show this help message
help:
	@echo "Usage: make [target]"
	@echo ""
	@echo "Targets:"
	@echo "  build    Build the application"
	@echo "  dev      Run in development mode"
	@echo "  test     Run all tests"
	@echo "  lint     Run linter"
	@echo "  fmt      Format code"
	@echo "  clean    Clean build artifacts"
	@echo "  deps     Install dependencies"

## build: Build the application
build:
	npm run build

## dev: Run in development mode
dev:
	npm run dev

## test: Run all tests
test:
	npm test

## lint: Run linter
lint:
	npm run lint

## fmt: Format code
fmt:
	npm run format

## clean: Clean build artifacts
clean:
	rm -rf dist node_modules/.cache

## deps: Install dependencies
deps:
	npm install
`

const pythonMakefileTemplate = `# Makefile for {{.Name}}
# Generated by cloud CLI

.PHONY: help run test lint fmt clean deps venv

.DEFAULT_GOAL := help

# Variables
APP_NAME := {{.Name}}
VENV := .venv
PYTHON := $(VENV)/bin/python
PIP := $(VENV)/bin/pip

## help: Show this help message
help:
	@echo "Usage: make [target]"
	@echo ""
	@echo "Targets:"
	@echo "  run      Run the application"
	@echo "  test     Run all tests"
	@echo "  lint     Run linter"
	@echo "  fmt      Format code"
	@echo "  clean    Clean build artifacts"
	@echo "  deps     Install dependencies"
	@echo "  venv     Create virtual environment"

## venv: Create virtual environment
venv:
	python -m venv $(VENV)

## deps: Install dependencies
deps: venv
	$(PIP) install -r requirements.txt
	$(PIP) install -r requirements-dev.txt

## run: Run the application
run:
	$(PYTHON) -m $(APP_NAME)

## test: Run all tests
test:
	$(PYTHON) -m pytest -v --cov=$(APP_NAME)

## lint: Run linter
lint:
	$(PYTHON) -m ruff check .
	$(PYTHON) -m mypy .

## fmt: Format code
fmt:
	$(PYTHON) -m ruff format .

## clean: Clean build artifacts
clean:
	rm -rf __pycache__ .pytest_cache .coverage htmlcov dist build *.egg-info
`

const rustMakefileTemplate = `# Makefile for {{.Name}}
# Generated by cloud CLI

.PHONY: help build run test lint fmt clean release

.DEFAULT_GOAL := help

# Variables
APP_NAME := {{.Name}}

## help: Show this help message
help:
	@echo "Usage: make [target]"
	@echo ""
	@echo "Targets:"
	@echo "  build    Build the application (debug)"
	@echo "  release  Build the application (release)"
	@echo "  run      Run the application"
	@echo "  test     Run all tests"
	@echo "  lint     Run clippy linter"
	@echo "  fmt      Format code"
	@echo "  clean    Clean build artifacts"

## build: Build the application (debug)
build:
	cargo build

## release: Build the application (release)
release:
	cargo build --release

## run: Run the application
run:
	cargo run

## test: Run all tests
test:
	cargo test

## lint: Run clippy linter
lint:
	cargo clippy -- -D warnings

## fmt: Format code
fmt:
	cargo fmt

## clean: Clean build artifacts
clean:
	cargo clean
`

const flutterMakefileTemplate = `# Makefile for {{.Name}}
# Generated by cloud CLI

.PHONY: help build-android build-ios build-web build-linux build-macos build-windows run test lint clean deps

.DEFAULT_GOAL := help

# Variables
APP_NAME := {{.Name}}

## help: Show this help message
help:
	@echo "Usage: make [target]"
	@echo ""
	@echo "Targets:"
	@echo "  run            Run the application"
	@echo "  test           Run all tests"
	@echo "  lint           Run analyzer"
	@echo "  clean          Clean build artifacts"
	@echo "  deps           Get dependencies"
	@echo "  build-android  Build Android APK"
	@echo "  build-ios      Build iOS app"
	@echo "  build-web      Build web app"
	@echo "  build-linux    Build Linux app"
	@echo "  build-macos    Build macOS app"
	@echo "  build-windows  Build Windows app"

## run: Run the application
run:
	flutter run

## test: Run all tests
test:
	flutter test

## lint: Run analyzer
lint:
	flutter analyze

## clean: Clean build artifacts
clean:
	flutter clean

## deps: Get dependencies
deps:
	flutter pub get

## build-android: Build Android APK
build-android:
	flutter build apk

## build-ios: Build iOS app
build-ios:
	flutter build ios

## build-web: Build web app
build-web:
	flutter build web

## build-linux: Build Linux app
build-linux:
	flutter build linux

## build-macos: Build macOS app
build-macos:
	flutter build macos

## build-windows: Build Windows app
build-windows:
	flutter build windows
`

const tauriMakefileTemplate = `# Makefile for {{.Name}}
# Generated by cloud CLI

.PHONY: help dev build build-debug test lint clean deps

.DEFAULT_GOAL := help

# Variables
APP_NAME := {{.Name}}

## help: Show this help message
help:
	@echo "Usage: make [target]"
	@echo ""
	@echo "Targets:"
	@echo "  dev          Run in development mode"
	@echo "  build        Build for production"
	@echo "  build-debug  Build for debugging"
	@echo "  test         Run all tests"
	@echo "  lint         Run linters"
	@echo "  clean        Clean build artifacts"
	@echo "  deps         Install dependencies"

## dev: Run in development mode
dev:
	npm run tauri dev

## build: Build for production
build:
	npm run tauri build

## build-debug: Build for debugging
build-debug:
	npm run tauri build -- --debug

## test: Run all tests
test:
	npm test
	cd src-tauri && cargo test

## lint: Run linters
lint:
	npm run lint
	cd src-tauri && cargo clippy

## clean: Clean build artifacts
clean:
	npm run clean
	cd src-tauri && cargo clean

## deps: Install dependencies
deps:
	npm install
	cd src-tauri && cargo fetch
`

const electronMakefileTemplate = `# Makefile for {{.Name}}
# Generated by cloud CLI

.PHONY: help dev build build-linux build-mac build-win test lint clean deps

.DEFAULT_GOAL := help

# Variables
APP_NAME := {{.Name}}

## help: Show this help message
help:
	@echo "Usage: make [target]"
	@echo ""
	@echo "Targets:"
	@echo "  dev          Run in development mode"
	@echo "  build        Build for current platform"
	@echo "  build-linux  Build for Linux"
	@echo "  build-mac    Build for macOS"
	@echo "  build-win    Build for Windows"
	@echo "  test         Run all tests"
	@echo "  lint         Run linter"
	@echo "  clean        Clean build artifacts"
	@echo "  deps         Install dependencies"

## dev: Run in development mode
dev:
	npm run dev

## build: Build for current platform
build:
	npm run build

## build-linux: Build for Linux
build-linux:
	npm run build:linux

## build-mac: Build for macOS
build-mac:
	npm run build:mac

## build-win: Build for Windows
build-win:
	npm run build:win

## test: Run all tests
test:
	npm test

## lint: Run linter
lint:
	npm run lint

## clean: Clean build artifacts
clean:
	rm -rf dist out node_modules/.cache

## deps: Install dependencies
deps:
	npm install
`

const reactNativeMakefileTemplate = `# Makefile for {{.Name}}
# Generated by cloud CLI

.PHONY: help start android ios test lint clean deps pod-install

.DEFAULT_GOAL := help

# Variables
APP_NAME := {{.Name}}

## help: Show this help message
help:
	@echo "Usage: make [target]"
	@echo ""
	@echo "Targets:"
	@echo "  start        Start Metro bundler"
	@echo "  android      Run on Android"
	@echo "  ios          Run on iOS"
	@echo "  test         Run all tests"
	@echo "  lint         Run linter"
	@echo "  clean        Clean build artifacts"
	@echo "  deps         Install dependencies"
	@echo "  pod-install  Install iOS pods"

## start: Start Metro bundler
start:
	npm start

## android: Run on Android
android:
	npm run android

## ios: Run on iOS
ios:
	npm run ios

## test: Run all tests
test:
	npm test

## lint: Run linter
lint:
	npm run lint

## clean: Clean build artifacts
clean:
	rm -rf node_modules/.cache
	cd android && ./gradlew clean
	cd ios && rm -rf build Pods

## deps: Install dependencies
deps:
	npm install

## pod-install: Install iOS pods
pod-install:
	cd ios && pod install
`

const wailsMakefileTemplate = `# Makefile for {{.Name}}
# Generated by cloud CLI

.PHONY: help dev build build-debug test lint clean

.DEFAULT_GOAL := help

# Variables
APP_NAME := {{.Name}}

## help: Show this help message
help:
	@echo "Usage: make [target]"
	@echo ""
	@echo "Targets:"
	@echo "  dev          Run in development mode"
	@echo "  build        Build for production"
	@echo "  build-debug  Build for debugging"
	@echo "  test         Run all tests"
	@echo "  lint         Run linters"
	@echo "  clean        Clean build artifacts"

## dev: Run in development mode
dev:
	wails dev

## build: Build for production
build:
	wails build

## build-debug: Build for debugging
build-debug:
	wails build -debug

## test: Run all tests
test:
	go test -v ./...
	cd frontend && npm test

## lint: Run linters
lint:
	golangci-lint run ./...
	cd frontend && npm run lint

## clean: Clean build artifacts
clean:
	rm -rf build/bin
	cd frontend && rm -rf dist node_modules/.cache
`
